/*
 * This source file was generated by the Gradle 'init' task
 */
package org.APCSLowell;

public class GoogleBillboard {
    public boolean isPrime(long n) {
        // Copy and paste your answer from CodingBat appropriatley here.
        if(n<2){
          return false;
        }
        for(int i=2; i<= Math.sqrt(n); i++){
          if(n%i==0){
            return false;
          }
        
        }
      return true;
    }
    public long firstPrimeNumberIn(String n) {
        long num=0;
        for(int i=0; i< n.length()-10;i++){
          num= Long.parseLong(n.substring(i,i+10));
          if(isPrime(num)){
            return num;
          }
        }
        return -1;
    }
}
